"""empty message

Revision ID: d338b8687b1b
Revises: 2584eb68b2f3
Create Date: 2025-09-11 10:59:05.244333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd338b8687b1b'
down_revision: Union[str, Sequence[str], None] = '2584eb68b2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) Почистим данные: NULL -> 0
    op.execute(sa.text("UPDATE users SET is_admin = 0 WHERE is_admin IS NULL"))

    # 2) Пересоздадим таблицу с нужным NULL-constraint
    with op.batch_alter_table("users", recreate="auto") as batch_op:
        batch_op.alter_column(
            "is_admin",
            existing_type=sa.Boolean(),
            nullable=False,
            # если хочешь БД-шный дефолт — оставь server_default=0;
            # если не нужен дефолт на уровне БД, выставь None.
            server_default=sa.text("0"),
            existing_server_default=None,
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
