"""empty message

Revision ID: d7fb7a0bdc78
Revises: b772ce624ea6
Create Date: 2025-09-26 15:16:57.445222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7fb7a0bdc78'
down_revision: Union[str, Sequence[str], None] = 'b772ce624ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('association_workout_exercises_workout_id_fkey'), 'association_workout_exercises', type_='foreignkey')
    op.drop_constraint(op.f('association_workout_exercises_exercise_id_fkey'), 'association_workout_exercises', type_='foreignkey')
    op.create_foreign_key(None, 'association_workout_exercises', 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'association_workout_exercises', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association_workout_exercises', type_='foreignkey')
    op.drop_constraint(None, 'association_workout_exercises', type_='foreignkey')
    op.create_foreign_key(op.f('association_workout_exercises_exercise_id_fkey'), 'association_workout_exercises', 'exercises', ['exercise_id'], ['id'])
    op.create_foreign_key(op.f('association_workout_exercises_workout_id_fkey'), 'association_workout_exercises', 'workouts', ['workout_id'], ['id'])
    # ### end Alembic commands ###
